"""Add content column to Note

Revision ID: c2c5dbb7de5f
Revises: 04f116bd1a6f
Create Date: 2025-07-29 16:37:10.710392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c5dbb7de5f'
down_revision: Union[str, Sequence[str], None] = '04f116bd1a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'content')
    # ### end Alembic commands ###
